### ISSUE TITLE
it's beautiful, but it doesn't show command when I use vrapper. I use sts 4.13.0. Even though I don't know whether can I call it the bug?

### ISSUE THREAD

**Issue by yaoqiangpersonal** [PyvesB/eclipse-planet-themes#10]

**Comment by PyvesB** [comment]
Hello @yaoqiangpersonal ! 👋🏻 

Thanks for reporting this. Could you please share screenshots of the "command" (I don't use Vrapper so I don't know what this is) with and without Planet Themes?

**Comment by PyvesB** [comment]
I've given Vrapper a quick try, and couldn't spot anything obviously wrong:
![Screenshot 2022-01-08 234945](https://user-images.githubusercontent.com/10694593/149664639-f2ddc090-d10a-4dc5-81ee-df6f55340425.png)

In the absence of any further information, I'll go ahead and close this issue.
