### ISSUE TITLE
[REQUEST] Solarized theme

### ISSUE THREAD

**Issue by 0xFF1E071F** [PyvesB/eclipse-planet-themes#11]
Hello dear developers
Can you please add solarized dark theme for eclipse.

Thank you very much

**Comment by PyvesB** [comment]
Hello @0xFF1E071F ! 👋🏻 

Feel free to submit a pull request. The CSS for the three existing themes can be used as a starting point: https://github.com/PyvesB/eclipse-planet-themes/tree/master/planet-themes-plugin/css 😉
