### ISSUE TITLE
[Improvement] Inverted Moon theme to match vscode light theme

### ISSUE THREAD

**Issue by gayanper** [PyvesB/eclipse-planet-themes#13]
Please introduce a new theme by inverting the current moon color theme so that only the editor parts become white and other parts will be grey scale. This will look very similar to vscode light theme.

**Comment by PyvesB** [comment]
Hello @gayanper ! 👋🏻 

Given https://github.com/gayanper/eclipse-themes, is the feature request still needed? If so, feel free to contribute to the project. 😉

**Comment by gayanper** [comment]
No @PyvesB we can close this issue.
