### ISSUE TITLE
Eclipse 4.15 CDT, theme not loading correctly

### ISSUE THREAD

**Issue by Arryk** [PyvesB/eclipse-planet-themes#15]
Hi,

I am trying to use those theme with the 4.15 version of Eclipse modified by Xilinx (Vitis 2021.1).
The theme do not work at all, see screenshot below of the Pluto theme loaded.

<img width="1920" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/1f6c2888-1ed4-4c67-83b4-797130420497">

Below the details of my eclipse installation on a Windows 11 22H2 machine.
<img width="833" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/f5e9bcea-d605-4fb4-9918-436818f5f85b">

Any idea how I could fix it so I can see the theme correctly ?

Thanks a lot!

**Comment by PyvesB** [comment]
Hello @Arryk! 👋🏻 

At the time of writing, the plugin doesn't properly support CDT, which is what is used as the C editor in your screenshot. To fix the problem, one would need to take the CSS values from [here](https://github.com/eclipse-cdt/cdt/blob/main/core/org.eclipse.cdt.ui/css/e4-dark_cdt.css), and add them to the [Moon](https://github.com/PyvesB/eclipse-planet-themes/blob/master/planet-themes-plugin/css/moon.css), [Neptune](https://github.com/PyvesB/eclipse-planet-themes/blob/master/planet-themes-plugin/css/neptune.css) and [Pluto](https://github.com/PyvesB/eclipse-planet-themes/blob/master/planet-themes-plugin/css/pluto.css) files with appropriate colour values.  :)

**Comment by Arryk** [comment]
Hi Pyves,

Thanks for the response, I guess I can give it a go and try to do that.
I have changed the title to reflect the fact that this issue is linked to CDT.

**Comment by Arryk** [comment]
Hi @PyvesB,

I have forked and cloned the project, it's been a while since I touched Java and Eclipse. I'm getting an error on the Plug-In validation for the project, this leads to the following compilation error:
``` org.osgi.framework.BundleException: Could not resolve module: com.codeaffine.workflow.persistence [14]```

Any idea how to fix this ?
<img width="412" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/e9d6bb0d-5ad0-432f-a930-4b05ba2ff0f1">

I also found something I don't understand, in 'moon.css' line 40, the org-eclipse-jdt-ui refers to '-neptune' instead of '-moon', is that normal ?
<img width="578" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/8ff0bd3a-b4a6-4f1b-8423-41ce8fa57aba">

I am using Eclipse RCP+RAP 2023-12 with JavaSE-17. The JRE ecosystem is very arcane, the project says I need JavaSE-8 but it is not available anymore.

**Comment by PyvesB** [comment]
> Any idea how to fix this ?

You probably did, but just double-checking to be on the safe side, can you confirm you followed the setup instructions in [this section of the README](https://github.com/PyvesB/eclipse-planet-themes#computer-code-contributions)?

> I also found something I don't understand, in 'moon.css' line 40, the org-eclipse-jdt-ui refers to '-neptune' instead of '-moon', is that normal ?

Oh, I think that's a copy-paste on my side. Nice catch! Feel free to submit a PR, I can also fix it on my side if you'd prefer! :)

**Comment by Arryk** [comment]
> You probably did, but just double-checking to be on the safe side, can you confirm you followed the setup instructions in [this section of the README](https://github.com/PyvesB/eclipse-planet-themes#computer-code-contributions)?

I tried again and followed every step, but the plugin "com.google.gson" is just nowhere to be found. Even after reloading the target, all plugin-ins are found except this one.

The weird thing is that the plugin is exists within eclipse, and shows up in the installation details:
<img width="809" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/4e379ffc-b6b4-489b-a395-8d186a3e5d71">

But "com.codeaffine.workflow.persistence" cannot resolve it
<img width="446" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/686b17cf-533f-4d1d-9dc7-88a83cb8e11a">

> Oh, I think that's a copy-paste on my side. Nice catch! Feel free to submit a PR, I can also fix it on my side if you'd prefer! :)

I can put it as part of the PR, it's easy enough (if I can get bloody Eclipse to work!)


EDIT:
I think I managed to get the thing to work after installing JRE 11 and resolving all the warnings, the plugin is still not found but the code now compiles.

**Comment by PyvesB** [comment]
I've pushed a commit that should fix the plugin not found error: 62921d9eb97eed003e98b7ed10c907cbddce4b7e

As far as JRE versions are concerned, I'll do some updates later to make things easier for newer Java versions, but seems like you're unlocked on that side for now :)

**Comment by Arryk** [comment]
> I've pushed a commit that should fix the plugin not found error: [62921d9](https://github.com/PyvesB/eclipse-planet-themes/commit/62921d9eb97eed003e98b7ed10c907cbddce4b7e)
> 
> As far as JRE versions are concerned, I'll do some updates later to make things easier for newer Java versions, but seems like you're unlocked on that side for now :)

Thanks, that fixed all the issues

I started the modification but the plugin export doesn't seem to work and I cannot add my plugin to Eclipse (4.30 nor 4.15)

<img width="596" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/5ff952cd-993d-416d-8870-b3646732f283">

<img width="729" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/c0f92648-07ae-46ea-b001-1bbcc244bb3b">

This is a common problem with Eclipse, I searched community but nothing works.
My current JRE is JavaSE-11 and I am targeting Eclipse 4.15

Any thought on this issue ?

**Comment by PyvesB** [comment]
>  the plugin export doesn't seem to work

What do you mean? Do you get a JAR generated at least? If that's the case, you can drop it into the `dropins` folder of one of your existing Eclipse installations, and restart it.

Alternatively, right-clicking on the plugin project and selecting `Run As` -> `Eclipse Application` will allow you to test things more easily by spinning up a temporary IDE environment. :)

**Comment by Arryk** [comment]
> What do you mean? Do you get a JAR generated at least? If that's the case, you can drop it into the `dropins` folder of one of your existing Eclipse installations, and restart it.

Yes, I generated a .jar file.
* If I use the `Help > Install New Software > Add > Archive` method, Eclipse tells me that nothing is available.
* If I put the .jar file into the dropins folder and restart eclipse, nothing happens and the plugin is not loaded.

> Alternatively, right-clicking on the plugin project and selecting Run As -> Eclipse Application will allow you to test things more easily by spinning up a temporary IDE environment. :)

`Run As -> Eclipse Application` works and I can see the plugins, now my issue is to successfully deploy this outside debugging environment.

Is there any way I can `Run As` with an other eclipse application ? I couldn't see any way of selecting a different version of eclipse.

Thanks

**Comment by PyvesB** [comment]
> * If I use the `Help > Install New Software > Add > Archive` method, Eclipse tells me that nothing is available.

Try right-clicking on the `planet-themes-feature` project, `Export...` in the menu, `Deployable features` in the list, and then select `Archive`. In your separate Eclipse installation, when you do `Help` > `Install New Software` > `Add` > `Archive`, make sure you unselect `Group items by category`.

> * If I put the .jar file into the dropins folder and restart eclipse, nothing happens and the plugin is not loaded.

This is odd, I've just tried this method out as well, and it works as expected for me. Do you not see the plug-in in the `About Eclipse` > `Installation details` > `Plug-ins` listing? When exporting the plug-in, here are the options I used on my side:
<img width="840" alt="Screenshot 2023-12-28 at 19 15 15" src="https://github.com/PyvesB/eclipse-planet-themes/assets/10694593/015afcd4-d1b9-4c6a-b862-00303ab8e151">

**Comment by Arryk** [comment]
Thanks, exporting the plugin as a feature instead of deployable plugins and fragment worked.
I will see if I can replicate the themes on CDT now

**Comment by Arryk** [comment]
Hi @PyvesB,

Hope you had a good break for Christmas and a good new year!

I started doing the port to CDT. I am missing some examples on how things should look like.

Any chance you could provides me with better real code screenshots for Pluto, Neptune & Moon ?

Something like:
* Inclusion statements
* Class definition and implementations
* Functions definition, functions calls
* ifdef equivalent ?
* Anything that can help me understand the theme a little bit better.


Here's is what I got so far

**Neptune**
<img width="1921" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/1b97a156-ab0f-4e58-a99e-ad00f4957d78">
<img width="551" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/06e22f18-66e6-4193-aed4-791633b90c22">


**Pluto**
<img width="1921" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/d50dbe2c-baa0-4295-80f1-7b3a8070c37d">

<img width="521" alt="image" src="https://github.com/PyvesB/eclipse-planet-themes/assets/12896037/db1329f1-b21a-4884-be7a-dad3e748d11e">

Any comment or advices on to improve the visual is welcome!

Thanks

**Comment by PyvesB** [comment]
Happy new year to you too! :)

Inclusion statements are import statements in Java, and there's not really an ifdef equivalent.

A couple of extra screenshots:
![pluto](https://github.com/PyvesB/eclipse-planet-themes/assets/10694593/3917c564-5131-42ca-a6dd-3951f1f1d9bc)
![neptune](https://github.com/PyvesB/eclipse-planet-themes/assets/10694593/edd5b669-85a8-49e6-9ab3-3f6d42657428)

Moon by and large sticks to the default syntax highlighting colour scheme, so unless anything looks off or is hard to read there, you can leave it alone.

From what I can tell, the screenshots look very promising, at least from the non-expert eye of someone who has not used CDT in earnest since 2016. Once you're happy with what you've got, we can ship a first version. If you notice something off later on, or if there's feedback from other users, we can always iterate and improve over time. :)

**Comment by PyvesB** [comment]
How are things going @Arryk , anything I can help with? :)

**Comment by Arryk** [comment]
Hi PyvesB,

Thanks for asking, I am extremely busy with work at the moment. Once I get some time back I'll complete the theme.

There is a strange behaviour I've seen with eclipse where when I start eclipse everything is white and I have to manually click on each workbench elements for the theme to be applied, this is quite annoying.

**Comment by PyvesB** [comment]
> There is a strange behaviour I've seen with eclipse where when I start eclipse everything is white and I have to manually click on each workbench elements for the theme to be applied, this is quite annoying.

Yes, this is probably #4. Never really managed to crack it, or come up with a minimal reproducible example. If you've got additional insights, do share them there :)

**Comment by PyvesB** [comment]
> There is a strange behaviour I've seen with eclipse where when I start eclipse everything is white and I have to manually click on each workbench elements for the theme to be applied, this is quite annoying.

I've decided to drop the flat scrollbars (5a69cebfe3cdba9eda7c685467cfd0f9ca60603c). This issue should no longer happen on the latest plugin revision.

> I also found something I don't understand, in 'moon.css' line 40, the org-eclipse-jdt-ui refers to '-neptune' instead of '-moon', is that normal ?

I've fixed this in 1fe8735c46fbd385e20b50a1ae4ca5c70aa3e896.

Hopefully things should be easier whenever you have a chance to pick this up again. :)

**Comment by Arryk** [comment]
I'll try to check this in the new few weeks and create a PR, thanks

**Comment by Arryk** [comment]
@PyvesB PR has been created
I can confirm the issue with the white panels is gone
