### ISSUE TITLE
Bugged views

### ISSUE THREAD

**Issue by 3r1u5** [PyvesB/eclipse-planet-themes#17]
when i have any of the themes active my outline and package explorer view are unusable, i can have the vies active but they have tiny text and are unreadable.

**Comment by PyvesB** [comment]
Hello @3r1u5 👋🏻 

Sorry to hear the themes are not working as expected for you. Could you please share screenshots of the issue?

**Comment by brkerez** [comment]
Hi! 
Same problem here ;) The Package explorer and Outline (not sure if anything else, I didn't research it too much) in the latest Eclipse version `2024-06`. It seems that the font is maybe extremely small or something but I can be wrong

I'm attaching the screenshot 
![image](https://github.com/PyvesB/eclipse-planet-themes/assets/313735/8ed8ce94-6c02-4ac4-9af5-f69f3a9d0aba)

**Comment by PyvesB** [comment]
Thanks for the additional details. I did some digging, seems that this is caused by the Xiliary dependency, which provides the flat scroll bars component. I've reported the issue here: https://github.com/fappel/xiliary/issues/116

**Comment by PyvesB** [comment]
I've decided to drop the flat scrollbars (5a69cebfe3cdba9eda7c685467cfd0f9ca60603c). This issue should no longer happen on Eclipse 2024-06 and version 0.3.0 of the plugin.

**Comment by brkerez** [comment]
I can confirm its fixed, thanks
