### ISSUE TITLE
Unreadable git uncomitted changes color on Moon theme

### ISSUE THREAD

**Issue by AObuchow** [PyvesB/eclipse-planet-themes#2]
I'm **loving** these themes so far, especially Neptune and Pluto!!

One thing I noticed: the git uncommitted changes background-color seems to be the same on all 3 themes. It seems OK for Neptune and Pluto, but on the Moon theme (and a light GTK theme such as Adwaita on Linux), the uncommitted changes foreground and background color are black.

![image](https://user-images.githubusercontent.com/10300119/87748044-e2bf6b80-c7c2-11ea-9842-77ce891e6d0f.png)

I can submit a PR for this if you'd like. The easiest fix is to set some CSS preferences for this, as it's [currently done in Spectrum theme](https://github.com/AObuchow/Eclipse-Spectrum-Theme/blob/master/com.aobuchow.themes.spectrum/css/preference_styles.css#L91).

However, you could also set this preference dynamically at runtime. This is something I'm currently experimenting with for Spectrum Theme. The advantage of this approach is that you can use Colors defined as ColorDefinitions to set preference colors (such as git uncommitted changes foreground/background color). However, this might be a bit overkill :P 
It makes sense for Spectrum theme as the user may change the theme's colors, and the git uncommitted changes color should follow suit.

**Comment by PyvesB** [comment]
Hello @AObuchow, thanks for reporting this. Actually, if you search for `UncommittedChangeBackgroundColor` in the repo, you'll notice that only Neptune and Pluto override. I've got a feeling that the preference got persisted by the workspace or Oomph. Does the same problem occur with the default Light theme?

**Comment by AObuchow** [comment]
@PyvesB you're right! This is occuring with the default Light theme as well. After some investigation, I'm almost certain is a new bug coming from Spectrum theme hahah :P Sorry about that... I better go fix that ;)

**Comment by PyvesB** [comment]
I'm wondering whether it would make sense to override `UncommittedChangeBackgroundColor` in Moon as well, just in case something else set the value to a different background in the user's preferences. What do you think?

**Comment by AObuchow** [comment]
@PyvesB I'm +1 for that idea, as the user can always override the Moon theme's preference.

**Comment by PyvesB** [comment]
> 
> 
> @PyvesB I'm +1 for that idea, as the user can always override the Moon theme's preference.

Done in the linked commit!
