### ISSUE TITLE
Slightly difficult to see the active bottom ctabfolder on multi page editor's with Pluto theme

### ISSUE THREAD

**Issue by AObuchow** [PyvesB/eclipse-planet-themes#3]
I think the Pluto theme is my favorite so far :) 

One thing I noticed, the SWT.BOTTOM CTabFolder's have the active highlight on the top. This is a matter of personal taste, but I find it a bit difficult to see the highlight, as it blends in with the bottom of the editor's outline (not sure if that's the correct term). The active tab in the below picture is "Category Definition":
![image](https://user-images.githubusercontent.com/10300119/87748765-ce7c6e00-c7c4-11ea-8680-7ec16e2c5432.png)

I'm not sure yet what solution I think is best, or if this is really an issue at all. You could move the active tab highlight to the bottom of the tab, as is done in Spectrum Theme, but this might look less elegant. From an aesthetic perspective, I like the way it looks currently, but the usability might be lessened a bit. 

I'm going to continue using the theme and see if my opinion changes, I might get used to it. Other users might not even notice this :)

**Comment by PyvesB** [comment]
Thanks for pointing this out, I had not really noticed! :)

What I'm slightly confused about is why the tab has no purple filling when it's an `SWT.BOTTOM` tab folder, even though it's active. Could this be a problem in the Platform?

**Comment by AObuchow** [comment]
> What I'm slightly confused about is why the tab has no purple filling when it's an `SWT.BOTTOM` tab folder, even though it's active. Could this be a problem in the Platform?

I'm running an IBuild of Eclipse that's a few weeks old, it's possible that the upstream bug for this was fixed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=564793?

**Comment by PyvesB** [comment]
Yes, I remember that one. I'm also running a older version, we should probably try with a later build. :)

**Comment by PyvesB** [comment]
Latest 4.17 version does not seem to improve things much out of the box.

A few new experiments below with 4.16.

With the tab outline - looks okay but it's one pixel too short on the left and the right, probably due to the fact that I'm not using the outer keyline:
![outline](https://user-images.githubusercontent.com/10694593/88206385-745d2c00-cc4e-11ea-9431-dd6e54580171.png)

With the highlight on top - does not help much IMO:
![highlight-top](https://user-images.githubusercontent.com/10694593/88206416-7cb56700-cc4e-11ea-8405-966395c777f6.png)

With the tab outline but no highlighter - would have been good, but one pixel gap:
![keyline-no-highlighter](https://user-images.githubusercontent.com/10694593/88207115-9b682d80-cc4f-11ea-9961-2b31a09708f5.png)

With the selected tab fill, as for normal CTabFolders - bogus:
![tab-fill](https://user-images.githubusercontent.com/10694593/88207251-cf435300-cc4f-11ea-908d-8a26c56e70e4.png)

I'm personally not super impressed with anything I've come up with so far. Any thoughts?

**Comment by AObuchow** [comment]
The first 3 options you showed look okay to me.
1. Looks good although like you said, it's unfortunate it's missing a pixel on the left and right side of the tab. 
2. Looks better in terms of not having lines of the same color overlap IMO
3. I actually think I quite like this look, although it adds more lines and maybe gives a less minimal look.

I also think the way it looks currently is also fine :) I wish I had a stronger opinion on what to suggest hahah

**Comment by ingomohr** [comment]
I don't know if that's helpful, but: I kind of like it the way it is in the current release build. :)
It doesn't clutter, and it's coherent (the Part's tab is filled if selected; the Part-internal tabs are not filled).

**Comment by PyvesB** [comment]
5th option: keep it as it is, but use a slightly lighter font size to emphasise the selected bottom tab.

![text-color](https://user-images.githubusercontent.com/10694593/88226059-ceb8b580-cc6b-11ea-8c31-64df7a09d3b4.png)

**Comment by ingomohr** [comment]
> 5th option: keep it as it is, but use a slightly lighter font size to emphasise the selected bottom tab.
> 
> 
> 
> ![text-color](https://user-images.githubusercontent.com/10694593/88226059-ceb8b580-cc6b-11ea-8c31-64df7a09d3b4.png)
> 
> 

This is imho the best of the options.
The only thing I have to mumble about is that the styling for non-selected Part-tabs low looks differently - which makes it three styles (if I'm right) compared to just two in the release build.
But I would still like the styling with that slightly brighter text color. 😊

**Comment by PyvesB** [comment]
@ingomohr thanks for the feedback!

I could use a brighter font for the selected but non active tab as well (e.g. "Search" in the screenshot above). That would bring it back to two styles if I've understood your reasoning correctly. It would also make it subtlely clearer to users that Search is the selected view in the non active part. 😉

**Comment by ingomohr** [comment]
> @ingomohr thanks for the feedback!
> 
> 
> 
> I could use a brighter font for the selected but non active tab as well (e.g. "Search" in the screenshot above). That would bring it back to two styles if I've understood your reasoning correctly. It would also make it subtlely clearer to users that Search is the selected view in the non active part. 😉 

Fair point. 😊 Yes, that would probably look rather nice.

**Comment by AObuchow** [comment]
@ingomohr @PyvesB I'm +1 for this suggestion :)

**Comment by PyvesB** [comment]
The fix is available in release 0.1.3!

**Comment by AObuchow** [comment]
Awesome, great work done here :D
