### ISSUE TITLE
Theme does not apply

### ISSUE THREAD

**Issue by AsutoraGG** [PyvesB/eclipse-planet-themes#6]
The background breaks when I try to open a new .java using this theme Is there a way to fix this?

https://user-images.githubusercontent.com/76235964/117453309-c3771200-af7f-11eb-8067-136c5ff95fa1.mp4

**Comment by PyvesB** [comment]
Hello @AsutoraGG ! 👋🏻

You should restart Eclipse after applying a theme change. Eclipse should normally display a popup inviting you to do so, but maybe that's being suppressed by the DevStyle plugin, which has the tendency to tamper with IDE behaviour. 😉

**Comment by AsutoraGG** [comment]
Apparently it was 😉 After removing DevStyle, this style started working! Thank you.

**Comment by PyvesB** [comment]
Glad to hear things are working smoothly now!
