### ISSUE TITLE
400: Invalid request

### ISSUE THREAD

**Issue by JUSTLOVELE** [PyvesB/eclipse-planet-themes#8]
hi, https://raw.githubusercontent.com/PyvesB/eclipse-planet-themes/updatesite, above website unable to access

**Comment by PyvesB** [comment]
Hello @JUSTLOVELE ! 👋🏻 

Thanks for reporting this. It looks like GitHub no longer exposes folders via their raw API. I'll see if other people have reported similar issues with their repositories and wait a few days for GitHub to fix it, otherwise I will need to publicise the update site differently.

**Comment by PyvesB** [comment]
The problem still seems to be occurring, and I haven't spotted any other reports after a quick search. I submitted a ticket to GitHub and also created a topic in the community forums: https://github.community/t/raw-url-suddenly-returning-invalid-request/203374

**Comment by PyvesB** [comment]
Still no response from GitHub on my bug report, and no response on the community thread either. After three weeks, I would have expected at least some sort of sign of life from GitHub support. I've gone ahead and switched the update site to https://cdn.jsdelivr.net/gh/PyvesB/eclipse-planet-themes@updatesite/

Let me know if you encounter any other problems! :)

**Comment by PyvesB** [comment]
I believe this report was in fact invalid. GitHub confirmed that nothing had recently changed with regards to raw folder handling, and I can still happily use https://raw.githubusercontent.com/PyvesB/eclipse-planet-themes/updatesite. It will indeed return an error when opened as is in a browser, but Eclipse handles it fine. I've reverted back to that update site and added a clarifying note in the Readme.
